apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: xkokavecs/ambulance-ufe
  newName: xkokavecs/ambulance-ufe
  newTag: 1.0.0  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú