apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: sk-ambulance-ufe-content
spec:
  microFrontend: sk-ambulance-ufe
  element: sk-ambulance-wl-app
  attributes:
    - name: base-path
      value: /sk-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?sk-ambulance-wl(/.*)?$"