apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: sk-ambulance-ufe-content
spec:
  microFrontend: sk-ambulance-ufe
  element: sk-ambulance-wl-app
  attributes:
    - name: api-base
      value: http://localhost:30081/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?ambulance-wl(/.*)?$"